owner: rizoma-tech
repo: status

sites:
  - name: API Gateway
    url: https://api.id.rizoma-tech.com/health
    expectedStatusCodes:
      - 200

  - name: Issuer Portal
    url: https://id.rizoma-tech.com
    expectedStatusCodes:
      - 200
      - 301

  - name: GDPR Scanner
    url: https://gdpr-scan.rizoma-tech.com
    expectedStatusCodes:
      - 200

  - name: Landing Page
    url: https://rizoma-tech.com
    expectedStatusCodes:
      - 200

  - name: Yalla Partners
    url: https://yalla.partners
    expectedStatusCodes:
      - 200


  - name: Credential Issuer Service
    url: https://issuer.id.rizoma-tech.com/.well-known/openid-credential-issuer
    expectedStatusCodes:
      - 200

  - name: Credential Verifier Service
    url: https://verifier.id.rizoma-tech.com/.well-known/openid-configuration
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status
  logoUrl: https://rizoma-tech.com/rizoma-r-logo.png
  name: Rizoma Status
  introTitle: "**Rizoma Technologies** system status"
  introMessage: Real-time availability of all Rizoma services. Checks run every 5 minutes.
  theme: light
  navbar:
    - title: Homepage
      href: https://rizoma-tech.com
    - title: GDPR Scanner
      href: https://gdpr-scan.rizoma-tech.com

workflowSchedule:
  uptime: "*/5 * * * *"
  graphs: "0 */6 * * *"
  staticSite: "0 */12 * * *"
  summary: "0 0 * * *"

i18n:
  footer: " "
